name: Check versioning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Get git context
      id: git-context
      run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }})"

    - name: Get commit
      if: github.event_name == 'pull_request'
      id: get-foo
      run: echo "::set-output name=foo::${{ github.event.pull_request.title }}"
    - name: Get commit
      if: github.event_name == 'push'
      id: get-foo
      run: echo "::set-output name=foo::${{ github.event.commits[0].message }}"

    - name: Output stuff
      run: |
        echo "context: ${{ steps.git-context.outputs.message }}"
        echo "context: ${{ steps.get-foo.outputs.foo }}"
        
    # # If PR title does contain "[SAME VERSION]", then do not check that version.txt is different from
    # # what is in master.
    # - if: github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[SAME VERSION]') == true
    #   name: Run version check
    #   run: ./version.sh -c -s
